### Filtering by one field
GET http://localhost:3000/api/users?filters[0][field]=name&filters[0][operator]=EQUAL&filters[0][value]=rafa

### Filtering by one field sorted
GET http://localhost:3000/api/users?filters[0][field]=name&filters[0][operator]=EQUAL&filters[0][value]=rafa&orderBy=name&order=ASC

### Filtering by two fileds sorted
GET http://localhost:3000/api/users?filters[0][field]=name&filters[0][operator]=EQUAL&filters[0][value]=rafa&filters[1][field]=surname&filters[1][operator]=EQUAL&filters[1][value]=gomez&orderBy=name&order=ASC

### Filtering by one field papginating
GET http://localhost:3000/api/users?filters[0][field]=name&filters[0][operator]=CONTAINS&filters[0][value]=Javi&pageSize=10&cursor=123123123&orderBy=created_at&order=DESC
