### Get filtered users
GET http://127.0.0.1:8000/users?filters[0][field]=email&filters[0][operator]=CONTAINS&filters[0][value]=javi&order=asc&orderBy=name&pageSize=10&pageNumber=1
Accept: application/json
